# version: '3.8'

# services:
#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

#   backend:
#     build:
#       context: ..
#       dockerfile: docker/Dockerfile
#     ports:
#       - "5000:5000"
#     environment:
#       - MONGO_URI=mongodb://mongodb:27017/bmad_agents
#     depends_on:
#       - mongodb

# volumes:
#   mongodb_data: {}


services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: bmad-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bmad-network

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: bmad-n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - bmad-network
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    depends_on:
      - mongodb

  # Backend API
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: bmad-backend
    ports:
      - "5000:5000"
    networks:
      - bmad-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bmad_agents
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/bmad-agent
    depends_on:
      - mongodb
      - n8n

  # Frontend React App
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: bmad-frontend
    ports:
      - "3000:3000"
    networks:
      - bmad-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    stdin_open: true

networks:
  bmad-network:
    driver: bridge

volumes:
  mongodb_data:
  n8n_data: